---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: groups-server-02
  name: groups-server-02
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: groups-server-02
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:
      labels:
        app: groups-server-02
    spec:
      containers:
      - env:
        image: groupsinfra/groups-server:groups-4.0.groups-4.0.0.cc795ee7.536.1032.1342
        args: ["--headless","--public", "--dedicated", "--max_retries", "100", "--map", "uro://2595c75f-4bcd-411f-992c-b20ad59030b1",
          "--server_name", "V-Sekai Preview Server Tokyo OSM", "--port", "7782"]
        imagePullPolicy: IfNotPresent
        name: groups-server-02
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
