---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: groups-server-02
  name: groups-server-02
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: groups-server-02
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:
      labels:
        app: groups-server-02
    spec:
      containers:
      - env:
        image: groupsinfra/groups-server:groups-4.2.groups-4.2.0.31eb49e5.596.1172.1443
        args: ["--headless","--public", "--dedicated", "--max_retries", "100", "--map", "uro://e23e9388-9bb6-46bf-9e26-496744659e43",
          "--server_name", "V-Sekai Preview Desert Light", "--port", "7802"]
        imagePullPolicy: IfNotPresent
        name: groups-server-02
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
