---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: groups-server-03
  name: groups-server-03
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: groups-server-03
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:
      labels:
        app: groups-server-03
    spec:
      containers:
      - env:
        image: groupsinfra/groups-server:groups-4.2.groups-4.2.0.db799f4c.688.1415.1631
        args: ["--headless","--public", "--dedicated", "--max_retries", "100", "--map", "uro://dddf8154-60a3-4c9f-888b-fb70c3e2655f/edit",
          "--server_name", "V-Sekai Haven", "--port", "7801"]
        imagePullPolicy: IfNotPresent
        name: groups-server-01
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
