---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: groups-server
  annotations:
    fluxcd.io/automated: "true"
  name: groups-server
  namespace: default
spec:
  # progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: groups-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:
      labels:
        app: groups-server
    spec:
      containers:
      - env:
        - name: FOO
          value: BAR
        image: groupsinfra/groups-server:v_sekai.6e7f5290.groups.d4b76200.20.125.54
        args: ["--public", "--dedicated", "--use_flat", "--map", "res://assets/scenes/maps/sky_celebration/sky_celebration.tscn",
          "--server_name", "kube", "--port", "7781"]
        imagePullPolicy: IfNotPresent
        name: groups-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
