---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: groups-server
  name: groups-server
  namespace: default
spec:
  # progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: groups-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:
      labels:
        app: groups-server
    spec:
      containers:
      - env:
        - name: FOO
          value: BAR
        image: groupsinfra/groups-server:groups-4.0.groups-4.0.0.1de2b617.458.693.1131
        args: ["--headless","--public", "--dedicated", "--max_retries", "100", "--map", "uro://bb7d83a8-a92d-4ba4-8e3f-233468c3e9db",
          "--server_name", "V-Sekai Kube Server", "--port", "7781"]
        imagePullPolicy: IfNotPresent
        name: groups-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
