apiVersion: v1
kind: Service
metadata:
  name: uro-stage
  namespace: default
  labels:
    app: uro-stage
spec:
  type: NodePort
  ports:
  - name: http-port
    port: 4000
    protocol: TCP
  selector:
    app: uro-stage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uro-stage-deployment
  namespace: default
  labels:
    app: uro-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uro-stage
  template:
    metadata:
      labels:
        app: uro-stage
    spec:
      serviceAccountName: cockroachdb
      volumes:
      - name: client-certs
        emptyDir: {}
      - name: static01-storage
        persistentVolumeClaim:
          claimName: static01-pvc
      initContainers:
      # The init-certs container sends a certificate signing request to the
      # kubernetes cluster.
      # You can see pending requests using: kubectl get csr
      # CSRs can be approved using:         kubectl certificate approve <csr name>
      #
      # In addition to the client certificate and key, the init-certs entrypoint will symlink
      # the cluster CA to the certs directory.
      - name: init-certs
        image: cockroachdb/cockroach-k8s-request-cert:0.4
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/ash"
        - "-ecx"
        - "/request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs -type=client\
          \ -user=uro-prod -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: client-certs
          mountPath: /cockroach-certs
      containers:
      - name: uro-stage
        env:
        - name: OAUTH2_DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: uro-prod
              key: discord-client-id
        - name: OAUTH2_DISCORD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: uro-prod
              key: discord-client-secret
        - name: OAUTH2_GITHuB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: uro-prod
              key: github-client-id
        - name: OAUTH2_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: uro-prod
              key: github-client-secret
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: uro-prod
              key: secret-key-base
        - name: PHOENIX_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: uro-prod
              key: secret-key-base
        - name: DATABASE_PASS
          valueFrom:
            secretKeyRef:
              name: uro-prod
              key: pass
        - name: DATABASE_URL
          value: "postgres://uro-prod@cockroachdb-public:26257/uro?sslmode=verify-full&sslcert=/cockroach-certs/client.uro-prod.crt&sslkey=/cockroach-certs/client.uro-prod.key&sslrootcert=/cockroach-certs/ca.crt"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: valkey-secret
              key: redis_url
        - name: FRONTEND_URL
          value: https://stage.v-sekai.org/
        - name: ROOT_ORIGIN
          value: https://stage.v-sekai.org
        - name: URL
          value: https://stage.v-sekai.org/api/v1/
        - name: PORT
          value: "4000"
        - name: JOKEN_SIGNER
          value: "todo"
        image: groupsinfra/uro:docker-uro_60ccf656.99
        imagePullPolicy: Always
        volumeMounts:
        - name: client-certs
          mountPath: /cockroach-certs
        - name: static01-storage
          mountPath: /app/uploads
          subPath: uploads
        ports:
        - containerPort: 4000
          name: http
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: uro-stage-frontend
  namespace: default
  labels:
    app: uro-stage-frontend
spec:
  type: NodePort
  ports:
  - name: http-port
    port: 3000
    protocol: TCP
  selector:
    app: uro-stage-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uro-stage-frontend-deployment
  namespace: default
  labels:
    app: uro-stage-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uro-stage-frontend
  template:
    metadata:
      labels:
        app: uro-stage-frontend
    spec:
      containers:
      - name: uro-stage-frontend
        env:
        - name: NEXT_PUBLIC_ORIGIN
          value: https://stage.v-sekai.org
        - name: API_ORIGIN
          value: http://uro-stage:4000
        - name: NEXT_PUBLIC_API_ORIGIN
          value: https://stage.v-sekai.org/api/v1
        image: groupsinfra/uro_frontend:docker-uro_60ccf656.99
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
      restartPolicy: Always
