apiVersion: v1
kind: Service
metadata:
  name: uro
  namespace: default
  labels:
    app: uro
spec:
  type: NodePort
  ports:
  - name: http-port
    port: 4000
    protocol: TCP
  selector:
    app: uro
